services:
  traefik:
    image: traefik:v3.7.8
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./dynamic:/dynamic:ro"
      - "./letsencrypt:/letsencrypt"  
    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      # API and Dashboard
      - "--api.insecure=false"
      - "--api.dashboard=true"
      # Docker Provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=khalednabeel01@gmail.com" 
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      # Observability i
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.khaledns.work.gd`)" 
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.middlewares=test-ratelimit@file"

    networks:
      - public
      - private1
      - private2
      - private3
  db:
    image: mysql:8.0
    logging:
      driver: "local"
    container_name: container_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    #cpus: "1.0"
    #mem_limit: 512m
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - private1
    restart: always
  backup-db:
    image: fradelg/mysql-cron-backup
    restart: unless-stopped
    user: "0:3004"
    depends_on:
      - db
    networks:
      - private1
    volumes:
      - backup:/backup
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASS: password
      MAX_BACKUPS: 15
      INIT_BACKUP: 1
      CRON_TIME: 0 0 * * *
      GZIP_LEVEL: 9    
  redis-cache:
    image: redis:7.4-alpine
    container_name: redis_cache
    restart: always
    command:
      - redis-server
      - --appendonly
      - "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - private1  

  backend:
    build: ./backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db

      REDIS_HOST: redis-cache
      REDIS_PORT: 6379

    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    expose:
      - "3000"
    #cpus: "1.0"
    #mem_limit: 512m
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:3000"]
      #interval: 10s
      #timeout: 5s
      #retries: 10
    networks:
      - private2
      - private1
      - private3
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`khaledns.work.gd`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.middlewares=test-ratelimit@file"
      - "traefik.http.routers.backend.priority=100"
      
  frontend:
    build: ./frontend
    logging:
      driver: local
    container_name: frontend
    depends_on:
      - backend
    expose:
      - "80"
    cpus: "0.25"
    mem_limit: 128m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - private2
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`khaledns.work.gd`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=1"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - private3
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - private3
      - private1
      - private2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.khaledns.work.gd`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=le"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.priority=20"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - private3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.khaledns.work.gd`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.priority=30"
  nodeExporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - private3
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/loki-config.yaml:ro
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - private3
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - private3
    depends_on:
      - loki
  alertmanager:
    image: prom/alertmanager
    privileged: true
    volumes:
          - ./monitoring/alertmanager.yml:/alertmanager.yml
    command:
        - '--config.file=/alertmanager.yml'
    expose:
        - "9093"
    networks:
      - private3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.khaledns.work.gd`)"
      - "traefik.http.routers.alertmanager.entrypoints=websecure"
      - "traefik.http.routers.alertmanager.tls=true"
      - "traefik.http.routers.alertmanager.tls.certresolver=le"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.http.routers.alertmanager.priority=70"
  telegrambot:
    image: metalmatze/alertmanager-bot:0.4.3
    container_name: telegrambot
    restart: unless-stopped
    command:
    - --alertmanager.url=http://alertmanager:9093
    - --telegram.token=8740043255:AAG4Plhy3jHJuInbgsk5-jObJEChQp7XRU0
    - --telegram.admin=6466183763
    - --store=bolt
    depends_on:
      - alertmanager
    expose:
      - "8080"
    networks:
      - private3    
volumes:
  mysql-data:
  grafana-data:
  redis-data:
  backup:
networks:
  public:
    name: public
  private1:
    name: private1
  private2:
    name: private2
  private3:
    name: private3
                           